export const GAMES = [
  {
    id: 'voxelcraft',
    appId: 'voxelcraft',
    title: 'Voxel Craft',
    tagline: 'Build. Break. Toast.',
    desc: 'An original blocky building sandbox — walk around a procedurally generated landscape in first person, break blocks, and place new ones. Built from scratch with three.js; not affiliated with any other block game.',
    size: '184 MB',
    gradient: ['#e2711d', '#5a3418'],
    glyph: '⛏️',
  },
  {
    id: 'game2048',
    appId: 'game2048',
    title: '2048',
    tagline: 'Merge your way to a loaf.',
    desc: 'The classic sliding-tile number puzzle, reimplemented from scratch with an original BredOS tile palette.',
    size: '4 MB',
    gradient: ['#f2a03d', '#8a5a2b'],
    glyph: '🔢',
  },
  {
    id: 'minesweeper',
    appId: 'minesweeper',
    title: 'BredSweeper',
    tagline: 'Clear the crumbs, not the mines.',
    desc: 'A original clone of the timeless flag-and-reveal puzzle, with three difficulty levels.',
    size: '3 MB',
    gradient: ['#8a5a2b', '#3e2110'],
    glyph: '💣',
  },
  {
    id: 'solitaire',
    appId: 'solitaire',
    title: 'BredCard Solitaire',
    tagline: 'A single-player classic.',
    desc: 'Click-to-move Klondike solitaire. Move one card at a time between the tableau and foundations.',
    size: '5 MB',
    gradient: ['#2f6b3a', '#1c3d21'],
    glyph: '🃏',
  },
  {
    id: 'flappyloaf',
    appId: 'flappyloaf',
    title: 'Flappy Loaf',
    tagline: 'Flap between the glasses.',
    desc: 'An original "tap to flap" arcade game — pilot a loaf of bread between endless glasses of milk. One tap of trouble.',
    size: '6 MB',
    gradient: ['#ffb35c', '#c9642f'],
    glyph: '🍞',
  },
  {
    id: 'toastfighter',
    comingSoon: true,
    title: 'Toast Fighter Arena',
    tagline: 'Coming soon',
    desc: 'A fictional fighting game shown only as box art for BredStore flavor — there is nothing behind this listing.',
    size: '—',
    gradient: ['#c94a2f', '#3e2110'],
    glyph: '🥊',
  },
]
